#!/bin/sh

. $GITR_HOME/git-fn

usage()
{
    log fatal "Usage: $0 $command <directory>*"
    exit -1
}

if [ $# -eq 0 ]
then
    usage
fi

command=$1
shift

while [ $# -gt 0 ]
do
    startDirectory=$1
    if [ ! -d "$startDirectory" ]
    then
        log warn "Directory $startDirectory does not exist - skipping..."
    else
        if [ -d "$startDirectory/.git" ]
        then
	    log verbose "----------------------------------------"
	    log verbose "-- $command $startDirectory"
	    log verbose "----------------------------------------"
	    log terse "$command $startDirectory"
            pushd "$startDirectory" >/dev/null
	    command_file=/tmp/`basename $0`-$$
            echo "$command" >>$command_file
	    chmod u+x $command_file
	    $command_file
	    rm $command_file
            popd >/dev/null 
        else
	    log verbose "-----------------------------------------------------------------------"
	    log verbose "-- Recursively processing $startDirectory"
	    log verbose "-----------------------------------------------------------------------"
            check_for_invalid_directories "$startDirectory"
            for directory in `find "$startDirectory" -type d -maxdepth 1 | sed 's/^\.\///' | grep -v ^$startDirectory$ | tr ' ' '\*'`
            do
                directory=`echo $directory | tr '\*' ' '`

                # Use $0 so this script works if this script isn't in your path...
                # Nice side-effect is that it also works if the script is renamed ;-)
                $0 "$command" "$directory"
            done
        fi
    fi

    shift
done
