#!/bin/sh

. `dirname $0`/git-fn

parse_opts $*
shift $shift

if [ $# -eq 0 ]
then
    git-recurse "git pull $dest_repo $source_branch$separator$dest_branch" .
else
    git-recurse "git pull $dest_repo $source_branch$separator$dest_branch" $*
fi
